# Configuration file for pipeline


files_to_grab:
  mat: GCF_000865085.1
  base_url: "https://hgdownload.gi.ucsc.edu/hubs/GCF/000/865/085/GCF_000865085.1/UShER_"
  more_url: "fluA.GCF_000865085.1."
  meta: ".latest.metadata.tsv.gz"   
  pb: ".latest.pb.gz"  
  
  segments:
    #PB2: NC_007373.1
    #PB1: NC_007372.1
    #PA: NC_007371.1
    HA: NC_007366.1
    #NP: NC_007369.1
    #NA: NC_007368.1
    #MP: NC_007367.1
    #NS: NC_007370.1  

#  mat: https://hgdownload.gi.ucsc.edu/hubs/GCF/000/865/085/GCF_000865085.1/UShER_NC_007366.1/

