name: flu-mut-rates

channels:
  - https://prefix.dev/conda-forge
  - https://prefix.dev/bioconda
  - nodefaults

dependencies:
  - snakemake
  - numpy
  - matplotlib
  - pandas
  - openpyxl
  - xlrd
  - seaborn
  - scipy
  - statsmodels
  - scikit-learn
  - bte
  - biopython
  - muscle
  - gffutils
  - notebook
  - ipywidgets
  - papermill
  - nbconvert
  - marimo
  - altair
  - gh
