from os import makedirs
import numpy as np
import pandas as pd
from itertools import product, permutations
from sklearn.metrics import mean_squared_error

letters = ["A", "C", "G", "T"]

# This script predicts rates without a pseudorate, so the rates at training and testing
# need to be positive. The model trains in log-space and the reported MSE and R^2 are
# for log rates.


def load_synonymous_muts(subtype=None):
    """
    Return a pandas dataframe for synonymous mutations at nucleotide sites with full
    length motifs (exclude the nucleotides at the start and end of a coding region).

    Data is loaded from results/site_specific_mutation_rates.csv, which is generated by
    the compute_rates notebook and contains mutation rates across all segments and hosts.

    Parameters:
        subtype (str or None): Legacy parameter for backward compatibility. Currently not
            used as the input data uses 'host' (all/human/avian) rather than subtype-level
            filtering. Pass None to use all data.

    Returns:
        pd.DataFrame: Synonymous mutations with full 3-mer motifs and required columns:
            mut_type, rate, motif, segment, mut_class
    """
    # Read in curated dataset. Unfortunately "NA" is a segment name.
    df = pd.read_csv("results/site_specific_mutation_rates.csv", keep_default_na=False)

    # Filter to synonymous mutations with full-length motifs from aggregated host data,
    # and drop sites in regions where synonymous rates are not a good neutral reference
    # (packaging signals and canonical splice junctions; flagged in compute_rates.ipynb).
    # Note: All synonymous mutations in the input already have 3-mer motifs
    query = (
        "mut_class=='synonymous' and motif.str.len()==3 "
        "and host=='all' and not exclude_from_mut_rate_analysis"
    )
    df.query(query, inplace=True)

    return df


class GeneralLinearModel:
    """
    A log-linear model for predicting rates by least squares with ridge regression.

    Attributes:
        included_factors (list): A list of model factors, which should be some
            combination of "local_context" and "global_context".
        W (dict): A dictionary mapping a mutation type to the model coefficients.
        tau_squared (dict): A dictionary mapping a mutation type to the MSE at training for log rates.
    """

    def __init__(self, included_factors):
        self.included_factors = included_factors
        self.W = {}
        self.tau_squared = {}

    def train(self, df_train):
        """
        Fit the model to the training data and fill the dictionaries self.W (model
        parameter values by mutation type) and self.tau_squareed (MSE by mutation type).

        Parameters:
            df_train  (pd.DatafFrame): A dataframe with columns "mut_type" and "rate".
                Additional columns are required based on self.included factors:
                "motif" for "local_context" and "segment" for "global_context".
        """
        # Initialise dictionaries for model parameters and remaining variances
        self.W = {}
        self.tau_squared = {}

        # Check which mutation types are present in the training data
        present_mut_types = df_train.mut_type.unique()

        # Make a separate fit for every mutation type
        for mut_type in present_mut_types:
            # Select the current mutation type
            df_mut_type = df_train.query("mut_type==@mut_type")

            # Prepare log-rates, dimensions: (# of sites, 1)
            log_rates = np.log(df_mut_type["rate"].values).reshape(-1, 1)

            # Create data matrix X, dimensions: (# of sites, # of parameters in model)
            X = self.create_data_matrix(df_mut_type.copy())

            # Fit a linear model as log_rates = w @ X using a mean squared loss with a
            # l2-regularization.
            regularization_strength = 0.1
            regularization_matrix = regularization_strength * np.identity(X.shape[1])
            regularization_matrix[0, 0] = 0  # (don't regularize the offset term)
            w = np.linalg.inv(X.T @ X + regularization_matrix) @ X.T @ log_rates

            # Store model parameters
            self.W[mut_type] = w
            # Store remaining variance on log counts
            self.tau_squared[mut_type] = mean_squared_error(log_rates, X @ w)

        return None

    def create_data_matrix(self, mut_counts_df):
        """
        Construct a numpy matrix, based on mut_counts_df, with the predictor variables
        of the model.

        Parameters:
            df_train  (pd.DatafFrame): Columns are required based on self.included factors:
                "motif" for "local_context" and "segment" for "global_context".
        """

        factor_cols = {
            "local_context": None,
            "global_context": None,
        }

        if "local_context" in self.included_factors:
            left_context = mut_counts_df["motif"].apply(lambda x: x[0]).values
            right_context = mut_counts_df["motif"].apply(lambda x: x[2]).values
            factor_cols["local_context"] = self.one_hot_l_r(left_context, right_context)
        if "global_context" in self.included_factors:
            factor_cols["global_context"] = self.one_hot_segment(mut_counts_df.segment)

        # Offset term
        base = np.full(len(mut_counts_df), 1)
        # Add columns depending on which model is fitted and which factors are included
        columns = [base]
        for factor in self.included_factors:
            if factor_cols[factor] is not None:
                columns += factor_cols[factor]

        # Compile data matrix
        X = np.column_stack(columns)

        return X

    def test(self, df_test):
        """
        Return a dictionary mapping mutation type to MSE for log rates.

        Parameters:
            df_test (pd.DatafFrame): A dataframe with columns "mut_type" and "rate".
                Additional columns are required based on self.included factors:
                "motif" for "local_context" and "segment" for "global_context".


        """
        mean_sq_errs = {}

        # Check which mutation types are present in the training data
        present_mut_types = df_test.mut_type.unique()

        # Compute mean squared error separately for every mutation type
        for mut_type in present_mut_types:
            # Select the current mutation type
            df_mut_type = df_test.query("mut_type==@mut_type")

            # Prepare log-counts, dimensions: (# of sites, 1)
            log_rates = np.log(df_mut_type["rate"].values).reshape(-1, 1)

            # Create data matrix X, dimensions: (# of sites, # of parameters in model)
            X = self.create_data_matrix(df_mut_type.copy())

            # Compute the mean squared error of the fitted model on the training data
            mean_sq_errs[mut_type] = mean_squared_error(
                log_rates, (X @ self.W[mut_type]).flatten()
            )

        return mean_sq_errs

    def add_predicted_rates(self, df):
        """
        Add columns "predicted_rate" (rate not log-rate) and "tau_squared" (MSE for
        log-rate, not rate) to the DataFrame.

        Parameters:
            df_train  (pd.DatafFrame): A dataframe with column "mut_type". Additional
                columns are required based on self.included factors: "motif" for
                "local_context" and "segment" for "global_context".
        """
        # Check which mutation types are present in the data
        present_mut_types = df.mut_type.unique()

        # Prepare array for predicted counts and remaining variance
        predicted_rates = np.empty(len(df))
        remaining_variance = np.empty(len(df))

        # Compute mean squared error separately for every mutation type
        for mut_type in present_mut_types:
            # Select the current mutation type
            mask_mut_type = (df.mut_type == mut_type).values
            df_mut_type = df[mask_mut_type]
            df_mut_type = df.query("mut_type==@mut_type")

            # Create data matrix X, dimensions: (# of sites, # of parameters in model)
            X = self.create_data_matrix(df_mut_type.copy())

            # Compute the mean squared error of the fitted model on the training data
            predicted_rates[mask_mut_type] = (X @ self.W[mut_type]).flatten()
            remaining_variance[mask_mut_type] = self.tau_squared[mut_type]

        df["predicted_rate"] = np.exp(predicted_rates)
        df["tau_squared"] = remaining_variance

    def per_site_expected_rates(self):
        """
        Return a DataFrame listing the predicted rate for each combination of predictor
        variable values (depending on self.included_factors).
        """
        segments = ["PB1", "NS", "NA", "HA", "PB2", "MP", "PA", "NP"]
        mut_types = list(self.W.keys())

        cols = ["mut_type"]
        thing = [mut_types]
        if "local_context" in self.included_factors:
            cols.append("left")
            cols.append("right")
            thing.append(letters)
            thing.append(letters)
        if "global_context" in self.included_factors:
            cols.append("segment")
            thing.append(segments)

        rows = list(product(*thing))
        rates_df = pd.DataFrame(data=rows, columns=cols)
        if "local_context" in self.included_factors:
            rates_df["motif"] = (
                rates_df.left + rates_df.mut_type.str.get(0) + rates_df.right
            )
            rates_df.drop(columns=["left", "right"], inplace=True)

        self.add_predicted_rates(rates_df)
        return rates_df

    @staticmethod
    def one_hot_l_r(context_l, context_r):
        """
        Return a one hot encoding of the left neighboring nucleotide and the right
        neighboring nucleotide.
        """
        sigma = {}
        for nt in ["C", "G", "T"]:
            sigma[nt + "_l"] = (context_l == nt).astype(int)
            sigma[nt + "_r"] = (context_r == nt).astype(int)

        return [
            sigma["C_l"],
            sigma["G_l"],
            sigma["T_l"],
            sigma["C_r"],
            sigma["G_r"],
            sigma["T_r"],
        ]

    @staticmethod
    def one_hot_segment(segments):
        """
        Return a one hot encoding of the segements.
        """
        segment_order = ["PB1", "NS", "NA", "HA", "PB2", "MP", "PA", "NP"]
        return [(segments == seg).values.astype(int) for seg in segment_order[1:]]


def fit_model(
    subtype, model_factors, expected_rates_outpath, performance_outpath
):
    """
    Fit a GeneralLinearModel to synonymous mutation data and write results.

    Parameters:
        subtype (str): The flu subtype. Use None to include all data.
        model_factors (list): A list of model factors, which should be some combination
            of "local_context" and "global_context".
        expected_rates_outpath (str): The path to write a csv of the per-site expected rate for each
            combination of predictor variable values.
        performance_outpath (str): The path to write a csv with MSE, variance, and R^2 for
            each mutation type.
    """
    df = load_synonymous_muts(subtype=subtype)
    model = GeneralLinearModel(included_factors=model_factors)
    model.train(df_train=df)

    rates_df = model.per_site_expected_rates()
    rates_df.to_csv(expected_rates_outpath, index=False)

    header = "mut_type,mse,var,r2\n"
    lines_to_write = []
    mse_on_train = model.test(df_test=df)
    for mut_type, mse in mse_on_train.items():
        log_mut_rate = np.log(df.query("mut_type==@mut_type").rate)
        var = np.var(log_mut_rate)
        r2 = 1 - mse / var
        lines_to_write.append(f"{mut_type},{mse},{var},{r2}\n")
    with open(performance_outpath, "w") as f:
        f.write(header)
        for line in lines_to_write:
            f.write(line)

    return None


def main():
    """
    Fit three nested models (base, local_context, local_context+global_context) to
    synonymous mutation rate data and write results to files.
    """
    model_hierarchy = [[], ["local_context"], ["local_context", "global_context"]]

    for model_factors in model_hierarchy:
        output_dir = f"results/neutral_model/"
        output_dir += "base" if len(model_factors) == 0 else "+".join(model_factors)
        makedirs(output_dir, exist_ok=True)

        expected_rates_outpath = f"{output_dir}/expected_rates_by_predictor.csv"
        performance_outpath = f"{output_dir}/model_performance.csv"

        fit_model(
            None, model_factors, expected_rates_outpath, performance_outpath
        )


if __name__ == "__main__":
    main()
